export const COMPANY_DETAILS = {
  name: "Servoca London",
  address: "38 Brennan House 610 High Road Leyton, London, England, E10 6RN",
  crn: "17048423",
  phone: "0208 088 5962",
  email: "info@servocalondon.co.uk",
  hours: "Mon - Fri: 09:00 - 18:00",
  vatNumber: "GB 123 4567 89",
};

export const SERVICES = [
  {
    id: "managed-it",
    title: "Managed IT Support",
    overview: "Comprehensive 24/7 monitoring and support for your entire IT infrastructure.",
    target: "SMEs looking for a dedicated external IT department.",
    process: [
      "Initial Infrastructure Audit",
      "Onboarding & Tool Deployment",
      "24/7 Monitoring & Helpdesk Support",
      "Monthly Performance Reviews",
    ],
    benefits: [
      "Reduced Downtime",
      "Predictable Monthly Costs",
      "Access to Expert Engineers",
    ],
    startingPrice: 499,
  },
  {
    id: "cloud-solutions",
    title: "Cloud Migration & Strategy",
    overview: "Seamless transition to Microsoft Azure or AWS with a focus on scalability and security.",
    target: "Businesses transitioning from legacy on-premise servers.",
    process: [
      "Cloud Readiness Assessment",
      "Migration Strategy Design",
      "Execution with Zero Downtime",
      "Post-Migration Optimization",
    ],
    benefits: [
      "Enhanced Scalability",
      "Remote Work Enablement",
      "Cost-Effective Infrastructure",
    ],
    startingPrice: 1500,
  },
  {
    id: "cyber-security",
    title: "Cyber Security & Compliance",
    overview: "Advanced threat protection and GDPR compliance auditing to protect your business assets.",
    target: "Companies handling sensitive data or requiring Cyber Essentials certification.",
    process: [
      "Vulnerability Scanning",
      "Security Policy Implementation",
      "Employee Awareness Training",
      "Compliance Certification Support",
    ],
    benefits: [
      "Protection Against Ransomware",
      "Regulatory Compliance",
      "Customer Trust Enhancement",
    ],
    startingPrice: 750,
  },
  {
    id: "it-consultancy",
    title: "Strategic IT Consultancy",
    overview: "Expert guidance on technology roadmaps to align IT with your business goals.",
    target: "Leadership teams planning digital transformation.",
    process: [
      "Business Goal Alignment",
      "Technology Gap Analysis",
      "Roadmap Development",
      "Vendor Selection & Management",
    ],
    benefits: [
      "Informed Decision Making",
      "Future-Proofed Technology",
      "ROI Maximization",
    ],
    startingPrice: 1200,
  },
  {
    id: "disaster-recovery",
    title: "Backup & Disaster Recovery",
    overview: "Robust data protection strategies ensuring your business stays operational after an incident.",
    target: "Businesses requiring high availability and data integrity.",
    process: [
      "Data Criticality Assessment",
      "Backup Solution Implementation",
      "Recovery Testing",
      "Continuity Plan Documentation",
    ],
    benefits: [
      "Peace of Mind",
      "Rapid Recovery Times",
      "Data Loss Prevention",
    ],
    startingPrice: 300,
  },
];

export const PRICING_PLANS = [
  {
    name: "Essential Support",
    price: 45,
    unit: "per user / month",
    features: [
      "Business Hours Helpdesk",
      "Remote Support",
      "Antivirus Management",
      "Patch Management",
      "Email Security",
    ],
    supportLevel: "Standard (9am - 5pm)",
    idealFor: "Small teams with basic IT needs",
    vatInfo: "Excluding VAT",
  },
  {
    name: "Professional",
    price: 75,
    unit: "per user / month",
    features: [
      "24/7 Helpdesk Access",
      "On-site Support Included",
      "Cloud Backup (100GB)",
      "Strategic IT Review (Quarterly)",
      "Advanced Threat Protection",
    ],
    supportLevel: "Priority 24/7",
    idealFor: "Growing businesses requiring high uptime",
    vatInfo: "Excluding VAT",
    popular: true,
  },
  {
    name: "Enterprise",
    price: "Custom",
    unit: "bespoke pricing",
    features: [
      "Dedicated Account Manager",
      "Full Infrastructure Management",
      "Unlimited Cloud Storage",
      "Cyber Essentials Plus Prep",
      "Disaster Recovery as a Service",
    ],
    supportLevel: "Dedicated VIP Support",
    idealFor: "Large organisations with complex requirements",
    vatInfo: "Contact for Quote",
  },
];
