export const COMPANY_DETAILS = {
  name: "Team24 Luton and Dunstable",
  address: "N/A",
  crn: "N/A",
  phone: "N/A",
  email: "N/A",
  hours: "Mon - Fri: 09:00 - 17:30",
};

export const SERVICES = [
  {
    id: "managed-it",
    title: "Managed IT Support",
    description: "Comprehensive end-to-end IT management for small to medium-sized enterprises in the UK.",
    target: "SMEs looking for reliable, proactive IT maintenance.",
    process: ["Audit", "Onboarding", "24/7 Monitoring", "Remote/On-site Support"],
    benefits: ["Reduced downtime", "Predictable costs", "Expert advice"],
    price: "£450/month",
  },
  {
    id: "cybersecurity",
    title: "Cybersecurity Solutions",
    description: "Protecting your business from evolving digital threats with advanced security protocols.",
    target: "Businesses handling sensitive data or requiring compliance.",
    process: ["Risk Assessment", "Implementation", "Staff Training", "Incident Response"],
    benefits: ["Data protection", "Peace of mind", "Compliance adherence"],
    price: "£299/month",
  },
  {
    id: "cloud-services",
    title: "Cloud Migration & Hosting",
    description: "Seamlessly transition your infrastructure to secure, scalable cloud environments.",
    target: "Companies looking to modernise and enable remote work.",
    process: ["Strategy", "Migration", "Optimisation", "Ongoing Management"],
    benefits: ["Scalability", "Accessibility", "Cost efficiency"],
    price: "£150/month",
  },
  {
    id: "it-consultancy",
    title: "IT Strategy & Consultancy",
    description: "Expert guidance to align your technology with your business goals.",
    target: "Leadership teams planning for growth or digital transformation.",
    process: ["Discovery", "Analysis", "Roadmap Creation", "Execution Support"],
    benefits: ["Strategic alignment", "Informed decisions", "Future-proofing"],
    price: "£1,200/project",
  },
  {
    id: "disaster-recovery",
    title: "Backup & Disaster Recovery",
    description: "Ensuring your data is safe and your business can recover quickly from any disaster.",
    target: "Any business that cannot afford data loss.",
    process: ["Backup Setup", "Testing", "Recovery Planning", "Monitoring"],
    benefits: ["Business continuity", "Data integrity", "Risk mitigation"],
    price: "£99/month",
  },
];

export const PRICING_PLANS = [
  {
    name: "Essential",
    price: "£199",
    period: "per user/month",
    features: ["Remote Support", "Antivirus Protection", "Email Security", "9-5 Helpdesk"],
    support: "Standard",
    idealFor: "Startups & Small Teams",
    vat: "Excluding VAT",
  },
  {
    name: "Professional",
    price: "£349",
    period: "per user/month",
    features: ["On-site Support", "Advanced Security", "Cloud Backup", "24/7 Monitoring", "Priority Helpdesk"],
    support: "Priority",
    idealFor: "Growing Businesses",
    vat: "Excluding VAT",
    popular: true,
  },
  {
    name: "Enterprise",
    price: "Custom",
    period: "tailored pricing",
    features: ["Dedicated Account Manager", "Full IT Strategy", "Unlimited Support", "Compliance Auditing", "Custom Infrastructure"],
    support: "Dedicated",
    idealFor: "Large Organisations",
    vat: "Excluding VAT",
  },
];
